### ISSUE TITLE
does not work on windows

### ISSUE THREAD

**Issue by lloiser** [foliveira/jscs-fixer#10]
unfortunately this does not work on windows (at least on win 8.1)
error message:

```
'C:\Users\Lukas.atom\packages\jscs-fixer\node_modules\jscs\bin\jscs' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.
```

The path `\Lukas.atom\` is definitely wrong. The correct path would be `\Lukas\.atom\`

**Comment by foliveira** [comment]
With the merge of PR #11 this one seems to closed.

**Comment by foliveira** [comment]
@lloiser [v0.3.0](https://github.com/foliveira/jscs-fixer/blob/v0.3.0/lib/jscsfixer.js) is published with this fix.

Thanks once again!
