### ISSUE TITLE
Show errors and warnings to the user

### ISSUE THREAD

**Issue by foliveira** [foliveira/jscs-fixer#12]
Find a away of showing errors and warnings to the user if something fails.

Got to decide on what's the best approach to handle this case:
- Show it on the bottom bar?
- Show as a notification?
- Just log it to the console?

**Comment by lloiser** [comment]
if bottom bar = status bar -> :-1: I rarely pay attention to the status bar (personal opinion)
I would suggest the notifications api of atom as soon as it is public (https://discuss.atom.io/t/notifications-api-stable/16070)

**Comment by varemenos** [comment]
The notification API sounds like the right approach.
If the user needs deeper information about his JSCS issues, he could use the jscs-linter

**Comment by foliveira** [comment]
Shipped with [v1.0.0](https://github.com/foliveira/jscs-fixer/tree/v1.0.0)

**Comment by foliveira** [comment]
Shipped with [v1.0.0](https://github.com/foliveira/jscs-fixer/tree/v1.0.0)
