### ISSUE TITLE
ES6 Support

### ISSUE THREAD

**Issue by ariririos** [foliveira/jscs-fixer#13]
Currently, jscs-fixer throws an error when it encounters ES6/ES2015 syntax (most notably, `import` and `let` statements).

linter-jscs allows ES6 use through a checkbox in the settings page, which enables use of the `--esprima=fb-esprima` option. Maybe jscs-fixer could do the same?

**Comment by foliveira** [comment]
Added to the milestone regarding the settings view. :+1: 

Thanks @rioc0719

**Comment by foliveira** [comment]
Closed by #14
