### ISSUE TITLE
Error: unrecognized flag --config

### ISSUE THREAD

**Issue by carlosagsmendes** [foliveira/jscs-fixer#16]
I get the following error when I'm trying to "Fix this file using JSCS" (only tested on windows):

Error: unrecognized flag --config
Try --help for options

D:\Repos\InnovationCast\xsd\xsd\app.jscsrc:5
    "requireCurlyBraces": [
                        ^
SyntaxError: Unexpected token :
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
C:\Users\Administrator.atom\packages\jscs-fixer\lib\jscsfixer.js:52 BufferedProcess.stderrC:\Users\Administrator\AppData\Local\atom\app-0.196.0\resources\app.asar\src\buffered-process.js:85 (anonymous function)events.js:77 emitOneevents.js:166 emit_stream_readable.js:146 readableAddChunk_stream_readable.js:109 Readable.pushnet.js:517 onread

Any ideas?

Thanks in advance

**Comment by foliveira** [comment]
Hi @carlosagsmendes!

That doesn't seem to be a valid `.jscsrc` file.

Care to post the whole content of it?

Thanks!

**Comment by carlosagsmendes** [comment]
Sure, here it is @foliveira:

{
    "excludeFiles": ["lib/**"],

```
"requireCurlyBraces": [
    "if",
    "else",
    "for",
    "while",
    "do",
    "try",
    "catch"
],
"requireOperatorBeforeLineBreak": true,
"requireCamelCaseOrUpperCaseIdentifiers": true,
"maximumLineLength": {
  "value": 100,
  "allowComments": true,
  "allowRegex": true
},

"validateQuoteMarks": "'",
"validateIndentation": "\t",
"disallowMultipleLineStrings": true,
"disallowMixedSpacesAndTabs": true,
"disallowTrailingWhitespace": true,
"disallowSpaceAfterPrefixUnaryOperators": true,
"disallowMultipleVarDecl": null,

"requireSpaceAfterKeywords": [
  "if",
  "else",
  "for",
  "while",
  "do",
  "switch",
  "return",
  "try",
  "catch"
],
"requireSpaceBeforeBinaryOperators": [
    "=", "+=", "-=", "*=", "/=", "%=", "<<=", ">>=", ">>>=",
    "&=", "|=", "^=", "+=",

    "+", "-", "*", "/", "%", "<<", ">>", ">>>", "&",
    "|", "^", "&&", "||", "===", "==", ">=",
    "<=", "<", ">", "!=", "!=="
],
"requireSpaceAfterBinaryOperators": true,
"requireSpacesInConditionalExpression": true,
"requireSpaceBeforeBlockStatements": true,
"requireLineFeedAtFileEnd": true,
"disallowSpacesInsideObjectBrackets": "all",
"disallowSpacesInsideArrayBrackets": "all",
"disallowSpacesInsideParentheses": true,

"validateJSDoc": {
    "checkParamNames": true,
    "requireParamTypes": true
},

"disallowMultipleLineBreaks": true,

"disallowCommaBeforeLineBreak": null,
"disallowDanglingUnderscores": null,
"disallowEmptyBlocks": null,
"disallowMultipleLineStrings": null,
"disallowTrailingComma": null,
"requireCommaBeforeLineBreak": null,
"requireDotNotation": null,
"requireMultipleVarDecl": null,
"requireParenthesesAroundIIFE": true
```

}

**Comment by carlosagsmendes** [comment]
@foliveira can you help? I wasn't able to sort this out. Thanks

**Comment by foliveira** [comment]
Hi @carlosagsmendes 

Can you give me the version of the `jscs` binary you're using.

It should be located in: `C:\Users\Administrator.atom\packages\jscs-fixer\node_modules\jscs\bin\jscs`

**Comment by foliveira** [comment]
Ah! Looking at it again, it seems you are trying to fix the `app.jscsrc` file?

That won't work. You need to fix `.js` files.

Also, `jscs` only recognises `.jscsrc` files. We still don't support feeding a rules file with another name to the tool.

**Comment by foliveira** [comment]
Closing as WontFix (see last comment)
