### ISSUE TITLE
Fix when file is not saved

### ISSUE THREAD

**Issue by lejafo** [foliveira/jscs-fixer#17]
The fixer correct files only when they are saved. It would be more convinient if it could fix style when file is not save yet.

**Comment by vomchik** [comment]
+1

**Comment by foliveira** [comment]
Hi @zejafo 

Will look into adding support for that, although I suspect it won't be easy since `jscs` only fixes files present on disk.

**Comment by lukejagodzinski** [comment]
Or at least add warning message that you need to save file to fix it. At first I thought that it does not work.

**Comment by foliveira** [comment]
Implemented with [v0.9.0](https://github.com/foliveira/jscs-fixer/tree/v0.9.0)
