### ISSUE TITLE
Error when fixing js file with jsx syntax in it

### ISSUE THREAD

**Issue by pauloabmiranda** [foliveira/jscs-fixer#18]
Hi,

Tried to fix a js file that has React jsx syntax in it and the error thrown is this:

Unexpected token < at \home\EventElem.js :

``` html
return (
    <a className={'event'} href={'events/details/' + this.props.event.Id} target="_self">
-----^
    <div className={imageElemClass} style={{backgroundImage: 'url(' + this.props.event.Image.replace('{0}', '405x188') + ')'}}> 
```

\packages\jscs-fixer\lib\jscsfixer.js:49 
1 code style error found.

Hope you can had support to jsx syntax.

Thanks

**Comment by foliveira** [comment]
Hi @pauloabmiranda,

I do think that jscs supports jsx syntax. It will probably be added as a configuration

Thanks

**Comment by foliveira** [comment]
Experimental version with JSX support ([v0.9.0](https://github.com/foliveira/jscs-fixer/tree/v0.9.0)) released.

Activate it in the package settings.

**Comment by pauloabmiranda** [comment]
Have updated and it is working.
Thanks
