### ISSUE TITLE
Doesn't recognize objects as values for requireDotNotation?

### ISSUE THREAD

**Issue by PaulOlteanu** [foliveira/jscs-fixer#19]
Currently I have

``` json
"requireDotNotation": {
    "allExcept": ["snake_case", "keywords"]
 }
```

And I get errors saying `requireDotNotation option requires a true value or "except_snake_case"`.

Is this not currently supported?

**Comment by foliveira** [comment]
Hi @LostCross

Can you provide a small test scenario, with .jscsrc and source file with the problem?

**Comment by PaulOlteanu** [comment]
@foliveira 

.jscsrc:

``` JSON
{
"requireDotNotation": {
        "allExcept": ["keywords"]
    }
}
```

test.js:

``` javascript
console.log('Test');
```

[Error screenshot](http://i.imgur.com/hehXCVC.png?1)

**Comment by foliveira** [comment]
@LostCross 

It was due to an outdated version of `jscs` being required. I pushed a new version with an updated version of `jscs`.

Update the package in your editor and let me know if the error persists.

Thanks!
