### ISSUE TITLE
Format on save

### ISSUE THREAD

**Issue by curtisblackwell** [foliveira/jscs-fixer#21]
Would it be possible (or is it already) to get a format on save option?

**Comment by foliveira** [comment]
Hi @curtisblackwell,

Will look into it in the next few days.

**Comment by f0rr0** [comment]
@curtisblackwell 

Use [atom-beautify](https://atom.io/packages/atom-beautify) with the jscs-fixer beautifier.
It has a beautify on save feature.

**Comment by foliveira** [comment]
@curtisblackwell I haven't been able to take on this as promised.

Feel free to contribute with a PR or follow @f0rr0's suggestion

Thanks
