### ISSUE TITLE
Set config for all projects

### ISSUE THREAD

**Issue by catacs** [foliveira/jscs-fixer#22]
I would like to have an option to set the .jscsrc file by default (For example ~/.jscsrc) instead of preset if it's not found in project directory. So the order can be:
1. Search in project directory
2. Search for default file
3. Use the selected preset

**Comment by catacs** [comment]
Hi, I have created the PR #24 extending the package with the specified feature.

**Comment by catacs** [comment]
Hello Fábio, are you going to take into account the PR  #24 ?

**Comment by foliveira** [comment]
Hi @catacs,

I'm closing this, after PR #24 has been merged and v1.1.0 published.

Thanks!

**Comment by catacs** [comment]
Oh that's great. Thanks
