### ISSUE TITLE
Is it support with "linter-eslint"?

### ISSUE THREAD

**Issue by thearabbit** [foliveira/jscs-fixer#25]
Is it support with "linter-eslint"?

**Comment by foliveira** [comment]
Hi @thearabbit 

The development for this plugin has stagnated.

This package doesn't use the **linter** package from Atom and it seems all the **linter** packages now offer auto fixing as this package offers.

Feel free to use them for a more complete experience or keeping using jscs-fixer to only get the fix stage

Thanks
