### ISSUE TITLE
How fix Unexpected token parsing react native JS ?

### ISSUE THREAD

**Issue by esutton** [foliveira/jscs-fixer#28]
I am trying to find a fixer that can help me with react native development.

**Settings**
- Default preset: **airbnb**
- [X] **ESS05 and JSX Support**

Is there a way to work-around this error?  Or maybe react native is too different from typical JS development?

`Unexpected token } at /Users/edward3/Documents/projects/react-native/field-planner-mobile/app/components/ViewProfile.js : 20 | TouchableHighlight, 21 | View, 22 |} from 'react-native'; ---------^ 23 | 24 |import Icon from 'react-native-vector-icons/MaterialIcons';`

```
import React from 'react';
import {
  Dimensions,
  Navigator,
  ScrollView,
  StyleSheet,
  Text,
  TouchableHighlight,  // <- Why unexpected token here?
  View,
} from 'react-native';
```

**Comment by foliveira** [comment]
Hi @esutton 

The development for this package has stagnated.

However from the report you send, it seems the culprit might be the comma after `View` and _jscs_ is just reporting a wrong line.

Also, you can use the **airbnb** preset by defining it on a `.jscsrc` file in your project
