### ISSUE TITLE
Cannot indent the file

### ISSUE THREAD

**Issue by Girish-K** [foliveira/jscs-fixer#29]
Error: Unknown node type ExportDeclaration. at Controller.traverse (/home/knolly/.atom/packages/jscs-fixer/node_modules/jscs/node_modules/estraverse/estraverse.js:521:31) at Object.traverse (/home/knolly/.atom/packages/jscs-fixer/node_modules/jscs/node_modules/estraverse/estraverse.js:713:27) at Object.iterate (/home/knolly/.atom/packages/jscs-fixer/node_modules/jscs/lib/tree-iterator.js:26:20) at Object.JsFile.iterate (/home/knolly/.atom/packages/jscs-fixer/node_modules/jscs/lib/js-file.js:511:29) at Object.JsFile._buildNodeIndex (/home/knolly/.atom/packages/jscs-fixer/node_modules/jscs/lib/js-file.js:992:14) at Object.JsFile (/home/knolly/.atom/packages/jscs-fixer/node_modules/jscs/lib/js-file.js:57:28) at StringChecker._createJsFileInstance (/home/knolly/.atom/packages/jscs-fixer/node_modules/jscs/lib/string-checker.js:227:16) at StringChecker.fixString (/home/knolly/.atom/packages/jscs-fixer/node_modules/jscs/lib/string-checker.js:247:25) at . (/home/knolly/.atom/packages/jscs-fixer/node_modules/jscs/lib/checker.js:72:27) at Array. (/home/knolly/.atom/packages/jscs-fixer/node_modules/jscs/node_modules/vow/lib/vow.js:712:39)

**Comment by foliveira** [comment]
Hi @Girish-K 

Can you provide some more info, since I'm not able to discern from your report what is wrong?

Thanks

**Comment by Girish-K** [comment]
Hi @**foliveira** 

When I was trying **fix this file using JSCS**, I got above-mentioned error.

![abc](https://cloud.githubusercontent.com/assets/11405748/19297743/764f1696-9065-11e6-972f-d6e457e63552.png)

Thanks

**Comment by foliveira** [comment]
Hi @Girish-K 

Aren't you missing a `/` in the very first line? The comment section seems to be invalid

**Comment by Girish-K** [comment]
Hi **@foliveira**

I don't think that is the issue. I removed the comments and tried it again and the same error occurred.

![abc](https://cloud.githubusercontent.com/assets/11405748/19306893/65159046-9095-11e6-8a5d-4c0e94dfdf71.png)
![abcd](https://cloud.githubusercontent.com/assets/11405748/19306892/650f1144-9095-11e6-910d-879e25461edd.png)

Thanks

**Comment by foliveira** [comment]
@Girish-K 

It seems it might be a problem with `esprima-fb` (it is deprecated). I've replaced that dependency with `babel-jscs` and published v1.2.1 for this package.

Can you update and test?

**Comment by Girish-K** [comment]
Hi **@foliveira**

Thanks, above mentioned error is fixed. 

But it is only displaying the errors and it is not fixing the JSCS errors.

![abc](https://cloud.githubusercontent.com/assets/11405748/19309363/ed5c8aac-90a1-11e6-8b38-2316b2bc9656.png)

**Comment by foliveira** [comment]
@Girish-K 

Those notifications seem to be from `linter-jscs`.

Also this package just calls `jscs --fix` on the open file, which means that if the standalone `jscs` tool can't fix the file it won't do so through this package.

Can you test from your terminal if doing a `jscs --fix <FILE_PATH>` does anything?

Please be aware that the `jscs` fix rules list is limited and might not be applied to all cases. Some might need to be corrected by hand.

Thanks

**Comment by foliveira** [comment]
Closing this - if need be, let's reopen to keep discussing this issue
