### ISSUE TITLE
Rule "disallowUnusedVariables" is not supported

### ISSUE THREAD

**Issue by myushchenko** [foliveira/jscs-fixer#30]
I have exception: Unsupported rule: disallowUnusedVariables.
But this rule is exist http://jscs.info/rule/disallowUnusedVariables
![image](https://cloud.githubusercontent.com/assets/768208/20173171/db4693c0-a740-11e6-93b0-6518b9717949.png)

**Comment by foliveira** [comment]
Hi @myushchenko 

Do you happen to have `ES2015 and JSX Support` enabled in the package settings?

**Comment by foliveira** [comment]
Hi @myushchenko 

Looking around it seems that the `disallowUnusedVariables` was introduced in `jscs@3.0.0`.

I just published a new version of the package with an updated dependency on `jscs`
